#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

config:
  version-candidate: VERSION
  dependencies:
    dependencies: [build]
    common: [build] # TODO: add 'release' once dependency-analysis works with tags

build:
  quality:
    filter:
      owner: graknlabs
      branch: master
    dependency-analysis:
      image: graknlabs-ubuntu-20.04
      command: |
        bazel run @graknlabs_dependencies//grabl/analysis:dependency-analysis
  correctness:
    build:
      image: graknlabs-ubuntu-20.04
      type: foreground
      command: |
        pyenv global 3.6.10
        sudo unlink /usr/bin/python3
        sudo ln -s $(which python3) /usr/bin/python3
        sudo ln -s /usr/share/pyshared/lsb_release.py /opt/pyenv/versions/3.6.10/lib/python3.6/site-packages/lsb_release.py
        ARTIFACT_USERNAME=$REPO_GRAKN_USERNAME \
        ARTIFACT_PASSWORD=$REPO_GRAKN_PASSWORD \
        bazel run @graknlabs_dependencies//distribution/artifact:create-netrc
        bazel build //...
        bazel test //tests:test_query --cache_test_results=no --test_output=streamed
#        bazel run @graknlabs_dependencies//tool/checkstyle:test-coverage
#        bazel test $(bazel query 'kind(checkstyle_test, //...)') --test_output=errors
#    test-concept:
#      image: graknlabs-ubuntu-20.04
#      type: foreground
#      command: |
#        pyenv global 3.6.10
#        sudo unlink /usr/bin/python3
#        sudo ln -s $(which python3) /usr/bin/python3
#        sudo ln -s /usr/share/pyshared/lsb_release.py /opt/pyenv/versions/3.6.10/lib/python3.6/site-packages/lsb_release.py
#        ARTIFACT_USERNAME=$REPO_GRAKN_USERNAME \
#        ARTIFACT_PASSWORD=$REPO_GRAKN_PASSWORD \
#        bazel run @graknlabs_dependencies//distribution/artifact:create-netrc
#        bazel test //:test_concept --test_output=errors
#    test-connection:
#      image: graknlabs-ubuntu-20.04
#      type: foreground
#      command: |
#        pyenv global 3.6.10
#        sudo unlink /usr/bin/python3
#        sudo ln -s $(which python3) /usr/bin/python3
#        sudo ln -s /usr/share/pyshared/lsb_release.py /opt/pyenv/versions/3.6.10/lib/python3.6/site-packages/lsb_release.py
#        ARTIFACT_USERNAME=$REPO_GRAKN_USERNAME \
#        ARTIFACT_PASSWORD=$REPO_GRAKN_PASSWORD \
#        bazel run @graknlabs_dependencies//distribution/artifact:create-netrc
#        bazel test //:test_connection --test_output=errors
#    test-query:
#      image: graknlabs-ubuntu-20.04
#      type: foreground
#      command: |
#        pyenv global 3.6.10
#        sudo unlink /usr/bin/python3
#        sudo ln -s $(which python3) /usr/bin/python3
#        sudo ln -s /usr/share/pyshared/lsb_release.py /opt/pyenv/versions/3.6.10/lib/python3.6/site-packages/lsb_release.py
#        ARTIFACT_USERNAME=$REPO_GRAKN_USERNAME \
#        ARTIFACT_PASSWORD=$REPO_GRAKN_PASSWORD \
#        bazel run @graknlabs_dependencies//distribution/artifact:create-netrc
#        bazel test //:test_query --test_output=errors
    deploy-pip-snapshot:
      image: graknlabs-ubuntu-20.04
      # TODO: should depend on tests
      dependencies: [build]
      filter:
        owner: graknlabs
        branch: master
      type: foreground
      command: |
        pyenv global 3.6.10
        sudo unlink /usr/bin/python3
        sudo ln -s $(which python3) /usr/bin/python3
        sudo ln -s /usr/share/pyshared/lsb_release.py /opt/pyenv/versions/3.6.10/lib/python3.6/site-packages/lsb_release.py
        ARTIFACT_USERNAME=$REPO_GRAKN_USERNAME \
        ARTIFACT_PASSWORD=$REPO_GRAKN_PASSWORD \
        bazel run @graknlabs_dependencies//distribution/artifact:create-netrc
        export DEPLOY_PIP_USERNAME=$REPO_GRAKN_USERNAME
        export DEPLOY_PIP_PASSWORD=$REPO_GRAKN_PASSWORD
        bazel run --define version=$(git rev-parse HEAD) //:deploy-pip -- snapshot
      # TODO: fix test-deployment
#    test-deployment:
#      image: graknlabs-ubuntu-20.04
#      dependencies: [deploy-pip-snapshot]
#      filter:
#        owner: graknlabs
#        branch: master
#      type: foreground
#      command: |
#        pyenv global 3.6.10
#        sudo unlink /usr/bin/python3
#        sudo ln -s $(which python3) /usr/bin/python3
#        sudo ln -s /usr/share/pyshared/lsb_release.py /opt/pyenv/versions/3.6.10/lib/python3.6/site-packages/lsb_release.py
#        ARTIFACT_USERNAME=$REPO_GRAKN_USERNAME \
#        ARTIFACT_PASSWORD=$REPO_GRAKN_PASSWORD \
#        bazel run @graknlabs_dependencies//distribution/artifact:create-netrc
#        bazel run //:grakn-extractor -- dist/grakn-core-server-linux
#        nohup ./dist/grakn-core-server-linux/grakn server start
#        sleep 60
#        echo -n "0.0.0-$GRABL_COMMIT" > VERSION
#        sed -i -e "s/CLIENT_PYTHON_VERSION_MARKER/$(cat VERSION)/g" test/deployment/requirements.txt
#        cat test/deployment/requirements.txt
#        pip install --upgrade pip
#        pip install -r test/deployment/requirements.txt
#        cd test/deployment/ && python -m unittest test

release:
  filter:
    owner: graknlabs
    branch: master
  validation:
    validate-dependencies:
      image: graknlabs-ubuntu-20.04
      command: bazel test //:release-validate-python-deps --test_output=streamed
  deployment:
    deploy-github:
      image: graknlabs-ubuntu-20.04
      command: |
        pyenv global 3.6.10
        sudo unlink /usr/bin/python3
        sudo ln -s $(which python3) /usr/bin/python3
        sudo ln -s /usr/share/pyshared/lsb_release.py /opt/pyenv/versions/3.6.10/lib/python3.6/site-packages/lsb_release.py
        pip install certifi
        export RELEASE_NOTES_TOKEN=$REPO_GITHUB_TOKEN
        bazel run @graknlabs_dependencies//tool/release:create-notes -- client-python $(cat VERSION) ./RELEASE_TEMPLATE.md
        bazel clean --expunge
        export DEPLOY_GITHUB_TOKEN=$REPO_GITHUB_TOKEN
        bazel run --define version=$(cat VERSION) //:deploy-github -- $GRABL_COMMIT
    deploy-pip-release:
      image: graknlabs-ubuntu-20.04
      command: |
        pyenv global 3.6.10
        sudo unlink /usr/bin/python3
        sudo ln -s $(which python3) /usr/bin/python3
        sudo ln -s /usr/share/pyshared/lsb_release.py /opt/pyenv/versions/3.6.10/lib/python3.6/site-packages/lsb_release.py
        export DEPLOY_PIP_USERNAME=$REPO_PYPI_USERNAME
        export DEPLOY_PIP_PASSWORD=$REPO_PYPI_PASSWORD
        bazel run --define version=$(cat VERSION) //:deploy-pip -- release
      dependencies: [deploy-github]
